#!/Users/sakuma/PycharmProjects/mmcif/venv/bin/python
import sys
from pdbecif.mmcif_io import CifFileReader
from pdbecif.mmcif_io import CifFileWriter
reader = CifFileReader()
args = sys.argv
cif_path = args[1]
cif_dict: dict = reader.read(cif_path, output='cif_dictionary')
cfd1 = CifFileWriter(args[2])
cfd1.write(cif_dict)
